FROM primetoninc/jdk:1.8

LABEL maintainer "luomin@caicloud.io"

ENV CONFIG_SERVER_PORT=8888
ENV ENABLE_EUREKA=true
ENV EUREKA_URL=http://eureka-server:8761/eureka
ENV CONFIG_SERVER_NAME=config-server

COPY ./caicloud-config-server/target/caicloud-config-server-0.0.1-SNAPSHOT.jar  /app.jar

ENTRYPOINT [ "sh","-c","java -jar $PARAM /app.jar"]